<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity Worker.
 *
 * This file is autogenerated with Symfony Maker Bundle.
 *
 * @ORM\Entity(repositoryClass="App\Repository\WorkerRepository")
 * @package App\Entity
 */
class Worker
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $surname;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return null|string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return Worker
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getSurname(): ?string
    {
        return $this->surname;
    }

    /**
     * @param string $surname
     *
     * @return Worker
     */
    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }
}
